version bump to 9.17.0
newrelic/newrelic-php-daemon-docker pull request #37
Opened 2021-03-03 09:23 UTC by danielocallaghan

Upgrade to Alpine 3.13

This Includes several security fixes:
https://alpinelinux.org/posts/Alpine-3.13.2-released.html

2021-03-03 09:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-php-daemon-docker?pullRequest=37) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-php-daemon-docker?pullRequest=37) before we can accept your contribution.<br/><hr/>**Daniel O'Callaghan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-php-daemon-docker?pullRequest=37) it.</sub>

2021-03-04 04:11 UTC, kneitinger requested changes
Hi @danielocallaghan this is great, thank you for your work and for bringing it to our attention!

I'm totally on board with the upgrade to 3.13, but we should modify the approach slightly.

I see why you created a `9.17.0` release, however, those versions/tags are intended to denote the version of the PHP Agent that is used.  For example, `9.9.0/Dockerfile` builds an image with version 9.9.0 of the PHP Agent.

Since the current latest release is still 9.16, could you instead implement the upgrade by changing the
```
FROM alpine:3.10 AS build
```
and
```
FROM alpine:3.10
```
lines in the _existing_ versions to `3.13` lines?

That way we still maintain the semantic relationship of image version to agent/daemon version.

I took a moment to test the oldest 5 releases on `3.13`, and they work well, so we're good to go on upgrading all of them!

Again, thanks so much!  Let me know if you have any questions or  more idea!

_**Edit:**_ Additionally, there is the [template Dockerfile](https://github.com/newrelic/newrelic-php-daemon-docker/blob/c5a02d08cb83fbf60166a4d7d0e3ff3525498e2e/Dockerfile-template).  An update to that would ensure that our release automation would use `3.13` for all future versions as well!

2021-03-04 09:31 UTC, danielocallaghan commented
Hi @kneitinger thanks for taking a look - sure thing I've just pushed an update, let me know if this approach works better for your conventions here 👍

2021-03-04 17:13 UTC, zsistla approved these changes
Thanks for contributing to our repo!

2021-03-04 17:35 UTC, merged